echo " "
echo "  Version: v2.6.0"
echo "  Author: @Caelifall | tiktok@欧米伽数码"
echo " "
echo " ======================================== "
echo " ==== "
echo " ====        Cracked by Chin "
echo " ==== "
echo " ======================================== "
echo " "
echo "  功能介绍"
echo "  • 三段式侧键|上拨&下拨"
echo "  • 魔方键|双击&长按拓展"
echo "  • 音量键|双击&长按拓展"
echo "  • 电源键|双击&长按拓展"
echo "  • 自定义| Shell 命令"
echo " "
echo "  配置方式"
echo "  • 一般情况|模块菜单 > WebUI 功能按钮"
echo "  • Magisk|通过KsuWebUI或WebUI X应用访问"
echo " "
echo "  支持设备|OPPO · 一加 · 真我"
echo " "
echo "  ✓ 模块安装完成"
echo " "
